[tool.black]
target-version = ["py39"]

[tool.ruff]
target-version = "py39"
exclude = [
    ".git",
    ".dvc",
    "outputs",
    "dataset_split",
]

[tool.ruff.lint]
extend-select = ["I"]  # import sorting
ignore = [
    "E402",  # allow imports after code in notebooks/scripts
]

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
allow_untyped_defs = true
allow_untyped_calls = true
follow_imports = "skip"
warn_unused_configs = true
exclude = "(outputs|dataset_split|.dvc)"
